.\" -*-Nroff-*-
.\" $Id: portfwd.cfg.5,v 1.2 2002/05/06 00:49:40 evertonm Exp $
.\""
.TH Portfwd 5 2002-05-05 "The Port Forwarding Daemon"
.\""
.SH NAME
portfwd.cfg \- Portfwd configuration file
.SH "DESCRIPTION"
This manual page documents briefly
.BR Portfwd
configuration syntax.
.PP
A future version of this document is expected to fully present the
configuration syntax.
.PP
For now, one should refer to the file 
.I conf.txt
and to configuration examples provided with Portfwd distribution.
.SH BUGS
Portfwd would benefit from a cleaner syntax for bind address specification.
.SH "SEE ALSO"
.TP
.IR "http://portfwd.sf.net"
Portfwd web site at SourceForge.
.br
.TP
portfwd(8)
Manual for Portfwd daemon.
.SH AUTHOR
Manual page loosely written by
.br
Éverton da Silva Marques <evertonsm at yahoo dot com dot br>

